/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsteammgmtsystem;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author sidbohra
 */
public class FixtureFinalTeamViewer extends javax.swing.JFrame {
    private int fixture_id;
    private DefaultTableModel data;

    public FixtureFinalTeamViewer() {
        initComponents();
    }
    public FixtureFinalTeamViewer(int fixtureId) {
        initComponents();
        this.fixture_id = fixtureId;
        showTableRecords();
    }

    public void showTableRecords(){
    
     data=(DefaultTableModel)table.getModel(); 
     table.getColumnModel().getColumn(0).setMaxWidth(80);
     table.getColumnModel().getColumn(0).setMinWidth(80); 
     table.getColumnModel().getColumn(1).setMaxWidth(100); 
     table.getColumnModel().getColumn(1).setMinWidth(100); 
     table.getColumnModel().getColumn(2).setMaxWidth(200);
     table.getColumnModel().getColumn(2).setMinWidth(200);
     table.getColumnModel().getColumn(3).setMaxWidth(250);
     table.getColumnModel().getColumn(3).setMinWidth(250);
     table.getColumnModel().getColumn(4).setMaxWidth(100); 
     table.getColumnModel().getColumn(4).setMinWidth(100);
     table.getColumnModel().getColumn(5).setMaxWidth(120); 
     table.getColumnModel().getColumn(5).setMinWidth(120);
     table.getColumnModel().getColumn(6).setMaxWidth(200); 
     table.getColumnModel().getColumn(6).setMinWidth(200);

  
    
     JTableHeader header=table.getTableHeader();//header is an object of JTableHEader class
     header.setFont(new Font ("Arial",Font.BOLD,16)); //heading
     table.setRowHeight(40);
     table.setGridColor(Color.blue);
     table.setShowGrid(true);
     table.setFont(new Font ("Arial",Font.BOLD,14)); //records
     data.setRowCount(0);
     try {
         Class.forName("java.sql.DriverManager");
         Connection con = ConnectDB.getConnect();
         Statement s = con.createStatement();
            ResultSet rr = s.executeQuery("SELECT student_id FROM participant_details WHERE fixture_id = " + this.fixture_id + " AND status = 'Approved'");         while(rr.next()){
             int student_id = rr.getInt("Student_ID");
             getTeamDetails(student_id);
         }
     } catch(Exception e) {
         
     }
    }
    
    public void getTeamDetails(int student_id){
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = ConnectDB.getConnect();
            Statement s = con.createStatement();
            
            ResultSet r = s.executeQuery("select * from student_details where student_id="+student_id);
            while(r.next()) {
                String studentName = r.getString("firstname")+" "+r.getString("lastname");
                String emailID = r.getString("Email_ID");
                String grade = r.getString("grade");
                String house = r.getString("house");
                String tutorName = r.getString("tutorname");
                data.addRow(new Object[]{false, student_id, studentName, emailID, grade, house, tutorName});
            }
                
        } catch(Exception e) {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AllUpcomingFixturesPanel = new javax.swing.JPanel();
        AUF_sp = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        FTV_back_btn = new javax.swing.JButton();
        STMS_lbl1 = new javax.swing.JLabel();
        STMS_lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AllUpcomingFixturesPanel.setBackground(new java.awt.Color(0, 102, 102));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Select", "Student ID", "Student Name", "Email ID", "Grade", "House", "Tutor Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AUF_sp.setViewportView(table);

        FTV_back_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        FTV_back_btn.setForeground(new java.awt.Color(0, 102, 102));
        FTV_back_btn.setText("Back");
        FTV_back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTV_back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AllUpcomingFixturesPanelLayout = new javax.swing.GroupLayout(AllUpcomingFixturesPanel);
        AllUpcomingFixturesPanel.setLayout(AllUpcomingFixturesPanelLayout);
        AllUpcomingFixturesPanelLayout.setHorizontalGroup(
            AllUpcomingFixturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllUpcomingFixturesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AUF_sp, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AllUpcomingFixturesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FTV_back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );
        AllUpcomingFixturesPanelLayout.setVerticalGroup(
            AllUpcomingFixturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllUpcomingFixturesPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AUF_sp, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FTV_back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        STMS_lbl1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        STMS_lbl1.setForeground(new java.awt.Color(0, 102, 102));
        STMS_lbl1.setText("Your Final Team");

        STMS_lbl2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        STMS_lbl2.setForeground(new java.awt.Color(0, 102, 102));
        STMS_lbl2.setText("Sports Team Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AllUpcomingFixturesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(STMS_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(STMS_lbl1)
                        .addGap(429, 429, 429))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(STMS_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(STMS_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AllUpcomingFixturesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FTV_back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTV_back_btnActionPerformed
        CoachMyFixture cmf = new CoachMyFixture();
        cmf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FTV_back_btnActionPerformed

    public void SaveFixtureTeamTransfer () {
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FixtureFinalTeamViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FixtureFinalTeamViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FixtureFinalTeamViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FixtureFinalTeamViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FixtureFinalTeamViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AUF_sp;
    private javax.swing.JPanel AllUpcomingFixturesPanel;
    private javax.swing.JButton FTV_back_btn;
    private javax.swing.JLabel STMS_lbl1;
    private javax.swing.JLabel STMS_lbl2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
