/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsteammgmtsystem;

/**
 *
 * @author sidbohra
 */
public class StudentDashboard extends javax.swing.JFrame {
            
    public StudentDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.msglabel.setText("Welcome"+" "+LoginPage.name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentDashboardPanel = new javax.swing.JPanel();
        SD_AllUpcomingFixtures_btn = new javax.swing.JButton();
        SD_MyUpcomingFixtures_btn = new javax.swing.JButton();
        SD_AllPastFixtures_btn = new javax.swing.JButton();
        SD_MyPastFixtures_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        msglabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentDashboardPanel.setBackground(new java.awt.Color(0, 102, 102));

        SD_AllUpcomingFixtures_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        SD_AllUpcomingFixtures_btn.setForeground(new java.awt.Color(0, 102, 102));
        SD_AllUpcomingFixtures_btn.setText("ALL UPCOMING FIXTURES");
        SD_AllUpcomingFixtures_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SD_AllUpcomingFixtures_btnActionPerformed(evt);
            }
        });

        SD_MyUpcomingFixtures_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        SD_MyUpcomingFixtures_btn.setForeground(new java.awt.Color(0, 102, 102));
        SD_MyUpcomingFixtures_btn.setText("MY UPCOMING FIXTURES");
        SD_MyUpcomingFixtures_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SD_MyUpcomingFixtures_btnActionPerformed(evt);
            }
        });

        SD_AllPastFixtures_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        SD_AllPastFixtures_btn.setForeground(new java.awt.Color(0, 102, 102));
        SD_AllPastFixtures_btn.setText("ALL PAST FIXTURES");
        SD_AllPastFixtures_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SD_AllPastFixtures_btnActionPerformed(evt);
            }
        });

        SD_MyPastFixtures_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        SD_MyPastFixtures_btn.setForeground(new java.awt.Color(0, 102, 102));
        SD_MyPastFixtures_btn.setText("MY PAST FIXTURES");
        SD_MyPastFixtures_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SD_MyPastFixtures_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentDashboardPanelLayout = new javax.swing.GroupLayout(StudentDashboardPanel);
        StudentDashboardPanel.setLayout(StudentDashboardPanelLayout);
        StudentDashboardPanelLayout.setHorizontalGroup(
            StudentDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentDashboardPanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(StudentDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SD_AllPastFixtures_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SD_AllUpcomingFixtures_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(StudentDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SD_MyUpcomingFixtures_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SD_MyPastFixtures_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );
        StudentDashboardPanelLayout.setVerticalGroup(
            StudentDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentDashboardPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(StudentDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SD_MyUpcomingFixtures_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SD_AllUpcomingFixtures_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(StudentDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SD_AllPastFixtures_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SD_MyPastFixtures_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(StudentDashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 660, 380));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Sports Team Management System");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        msglabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        msglabel.setForeground(new java.awt.Color(0, 102, 102));
        msglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(msglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SD_AllUpcomingFixtures_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SD_AllUpcomingFixtures_btnActionPerformed
            AllUpcomingFixtures auf = new AllUpcomingFixtures(LoginPage.name);
            auf.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_SD_AllUpcomingFixtures_btnActionPerformed

    private void SD_AllPastFixtures_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SD_AllPastFixtures_btnActionPerformed
        AllPastFixtures pf = new AllPastFixtures();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SD_AllPastFixtures_btnActionPerformed

    private void SD_MyUpcomingFixtures_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SD_MyUpcomingFixtures_btnActionPerformed
        StudentMyFixture obj = new StudentMyFixture();
        obj.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_SD_MyUpcomingFixtures_btnActionPerformed

    private void SD_MyPastFixtures_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SD_MyPastFixtures_btnActionPerformed
        StudentPastFixtures spf = new StudentPastFixtures();
        spf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SD_MyPastFixtures_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SD_AllPastFixtures_btn;
    private javax.swing.JButton SD_AllUpcomingFixtures_btn;
    private javax.swing.JButton SD_MyPastFixtures_btn;
    private javax.swing.JButton SD_MyUpcomingFixtures_btn;
    private javax.swing.JPanel StudentDashboardPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel msglabel;
    // End of variables declaration//GEN-END:variables

    private void setlocationRelativeto() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
