/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsteammgmtsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static sportsteammgmtsystem.LoginPage.category;
import static sportsteammgmtsystem.LoginPage.email;

/**
 *
 * @author sidbohra
 */
public class StudentSignUp extends javax.swing.JFrame {
 
    
    private int studentID, schoolID, coachID;
    String firstName;
    private String lastName, grade, house, tutorName, emailID, ageGroup, gender, sport;
    public StudentSignUp(String firstName, String lastName, String emailID) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.firstName=firstName;
        this.lastName=lastName;
        this.emailID=emailID;
            this.SSU_SchoolID_txt.setText("600707");
    }  
    private StudentSignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup_Student_btngrp = new javax.swing.ButtonGroup();
        StudentSignUpWholePanel = new javax.swing.JPanel();
        STMS_lbl5 = new javax.swing.JLabel();
        StudentSignUpPanel = new javax.swing.JPanel();
        SSU_StudentID_lbl = new javax.swing.JLabel();
        SSD_Sport_lbl = new javax.swing.JLabel();
        SSU_Back_btn = new javax.swing.JButton();
        SSU_Submit_btn = new javax.swing.JButton();
        SSU_Gender_btn = new javax.swing.JPanel();
        SSU_Male_radbtn = new javax.swing.JRadioButton();
        SSU_Female_radbtn = new javax.swing.JRadioButton();
        SSU_Coach_lbl = new javax.swing.JLabel();
        SSU_FormTutor_lbl = new javax.swing.JLabel();
        SSU_Grade_lbl = new javax.swing.JLabel();
        SSU_AgeGroup_lbl = new javax.swing.JLabel();
        SSU_Grade_cb = new javax.swing.JComboBox<>();
        SSU_AgeGroup_cb = new javax.swing.JComboBox<>();
        SSU_FormTutor_txt = new javax.swing.JTextField();
        SSU_Sport_cb = new javax.swing.JComboBox<>();
        SSU_House_lbl = new javax.swing.JLabel();
        SSU_House_cb = new javax.swing.JComboBox<>();
        SSU_SchoolID_lbl = new javax.swing.JLabel();
        SSU_SchoolID_txt = new javax.swing.JTextField();
        SSU_StudentID_txt = new javax.swing.JTextField();
        SSU_Reset_btn = new javax.swing.JButton();
        SSU_Coach_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentSignUpWholePanel.setBackground(new java.awt.Color(255, 255, 255));

        STMS_lbl5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        STMS_lbl5.setForeground(new java.awt.Color(0, 102, 102));
        STMS_lbl5.setText("Sports Team Management System");

        StudentSignUpPanel.setBackground(new java.awt.Color(0, 102, 102));

        SSU_StudentID_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SSU_StudentID_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SSU_StudentID_lbl.setText("Student ID");

        SSD_Sport_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SSD_Sport_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SSD_Sport_lbl.setText("Sport");

        SSU_Back_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        SSU_Back_btn.setForeground(new java.awt.Color(0, 102, 102));
        SSU_Back_btn.setText("Back");
        SSU_Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSU_Back_btnActionPerformed(evt);
            }
        });

        SSU_Submit_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        SSU_Submit_btn.setForeground(new java.awt.Color(0, 102, 102));
        SSU_Submit_btn.setText("Submit");
        SSU_Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSU_Submit_btnActionPerformed(evt);
            }
        });

        SSU_Gender_btn.setBackground(new java.awt.Color(255, 255, 255));
        SSU_Gender_btn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N

        signup_Student_btngrp.add(SSU_Male_radbtn);
        SSU_Male_radbtn.setText("Male");

        signup_Student_btngrp.add(SSU_Female_radbtn);
        SSU_Female_radbtn.setText("Female");
        SSU_Female_radbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSU_Female_radbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SSU_Gender_btnLayout = new javax.swing.GroupLayout(SSU_Gender_btn);
        SSU_Gender_btn.setLayout(SSU_Gender_btnLayout);
        SSU_Gender_btnLayout.setHorizontalGroup(
            SSU_Gender_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SSU_Gender_btnLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(SSU_Male_radbtn)
                .addGap(37, 37, 37)
                .addComponent(SSU_Female_radbtn)
                .addGap(63, 63, 63))
        );
        SSU_Gender_btnLayout.setVerticalGroup(
            SSU_Gender_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SSU_Gender_btnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SSU_Gender_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSU_Male_radbtn)
                    .addComponent(SSU_Female_radbtn))
                .addGap(38, 38, 38))
        );

        SSU_Coach_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SSU_Coach_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SSU_Coach_lbl.setText("Coach");

        SSU_FormTutor_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SSU_FormTutor_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SSU_FormTutor_lbl.setText("Form Tutor");

        SSU_Grade_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SSU_Grade_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SSU_Grade_lbl.setText("Grade");

        SSU_AgeGroup_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SSU_AgeGroup_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SSU_AgeGroup_lbl.setText("Sports Age Group");

        SSU_Grade_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Year 7", "Year 8", "Year 9", "Year 10", "Year 11", "Year 12", "Year 13", " " }));

        SSU_AgeGroup_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "U12", "U13", "U14", "U15", "U16", "U17", "U18" }));

        SSU_FormTutor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSU_FormTutor_txtActionPerformed(evt);
            }
        });

        SSU_Sport_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Volleyball", "Football", "Basketball", "Rugby", "Tennis", "Badminton", "Swimming", "Cross Country", "Table Tennis", "Netball" }));
        SSU_Sport_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSU_Sport_cbActionPerformed(evt);
            }
        });

        SSU_House_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SSU_House_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SSU_House_lbl.setText("House");

        SSU_House_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Da Vinci", "Einstein", "Fleming", "Nansen", "Rutherford", "Wilberforce", " " }));

        SSU_SchoolID_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SSU_SchoolID_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SSU_SchoolID_lbl.setText("School ID");

        SSU_SchoolID_txt.setEditable(false);
        SSU_SchoolID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSU_SchoolID_txtActionPerformed(evt);
            }
        });

        SSU_StudentID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSU_StudentID_txtActionPerformed(evt);
            }
        });

        SSU_Reset_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        SSU_Reset_btn.setForeground(new java.awt.Color(0, 102, 102));
        SSU_Reset_btn.setText("Reset");
        SSU_Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSU_Reset_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentSignUpPanelLayout = new javax.swing.GroupLayout(StudentSignUpPanel);
        StudentSignUpPanel.setLayout(StudentSignUpPanelLayout);
        StudentSignUpPanelLayout.setHorizontalGroup(
            StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SSU_StudentID_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SSU_Coach_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SSD_Sport_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SSU_Grade_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SSU_House_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SSU_FormTutor_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SSU_FormTutor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSU_Grade_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSU_House_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSU_StudentID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSU_Sport_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSU_Coach_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                        .addComponent(SSU_AgeGroup_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SSU_AgeGroup_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentSignUpPanelLayout.createSequentialGroup()
                            .addComponent(SSU_Submit_btn)
                            .addGap(18, 18, 18)
                            .addComponent(SSU_Reset_btn)
                            .addGap(18, 18, 18)
                            .addComponent(SSU_Back_btn)
                            .addGap(18, 18, 18))
                        .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                            .addComponent(SSU_SchoolID_lbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SSU_SchoolID_txt))
                        .addComponent(SSU_Gender_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        StudentSignUpPanelLayout.setVerticalGroup(
            StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSU_StudentID_lbl)
                    .addComponent(SSU_AgeGroup_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSU_AgeGroup_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSU_StudentID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSD_Sport_lbl)
                            .addComponent(SSU_Sport_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSU_Coach_lbl)
                            .addComponent(SSU_Coach_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSU_FormTutor_lbl)
                            .addComponent(SSU_FormTutor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSU_Grade_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SSU_Grade_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSU_House_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SSU_House_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                        .addComponent(SSU_Gender_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSU_SchoolID_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SSU_SchoolID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSU_Submit_btn)
                            .addComponent(SSU_Back_btn)
                            .addComponent(SSU_Reset_btn))))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StudentSignUpWholePanelLayout = new javax.swing.GroupLayout(StudentSignUpWholePanel);
        StudentSignUpWholePanel.setLayout(StudentSignUpWholePanelLayout);
        StudentSignUpWholePanelLayout.setHorizontalGroup(
            StudentSignUpWholePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentSignUpWholePanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(StudentSignUpWholePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentSignUpWholePanelLayout.createSequentialGroup()
                        .addComponent(StudentSignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentSignUpWholePanelLayout.createSequentialGroup()
                        .addComponent(STMS_lbl5)
                        .addGap(273, 273, 273))))
        );
        StudentSignUpWholePanelLayout.setVerticalGroup(
            StudentSignUpWholePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentSignUpWholePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(STMS_lbl5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StudentSignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentSignUpWholePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentSignUpWholePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SSU_Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSU_Back_btnActionPerformed
       SignUp lp=new SignUp(this.firstName,this.lastName,this.emailID); 
            lp.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_SSU_Back_btnActionPerformed

    private void SSU_Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSU_Submit_btnActionPerformed
       
        
        if(validateEntries()==true)
            insertRecords();  ///insert in db table student_details
    }//GEN-LAST:event_SSU_Submit_btnActionPerformed
public boolean validateEntries(){
    boolean flag=true;
    if(this.SSU_StudentID_txt.getText().isEmpty()){
        flag=false;
        JOptionPane.showMessageDialog(this, "Please enter your Student ID");}
        else if(this.SSU_FormTutor_txt.getText().isEmpty()){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please enter your Form Tutor");
        }  else if(this.SSU_AgeGroup_cb.getSelectedItem().toString().equals("Select")){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please select your Age Group");       
        } else if(this.SSU_House_cb.getSelectedItem().toString().equals("Select")){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please select your House");
        } else if(this.SSU_Grade_cb.getSelectedItem().toString().equals("Select")){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please select your Grade");
        } else if(!this.SSU_Male_radbtn.isSelected() && !this.SSU_Female_radbtn.isSelected()){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please Select Your Gender");}
        else if(this.SSU_Sport_cb.getSelectedItem().toString().equals("Select")){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please Select Your Sport");}
    
    if(flag){
            this.studentID = Integer.parseInt(this.SSU_StudentID_txt.getText());
            this.tutorName = this.SSU_FormTutor_txt.getText();
             getCoachId();
             
             this.schoolID=003257;
             this.ageGroup=this.SSU_AgeGroup_cb.getSelectedItem().toString();
             this.house=this.SSU_House_cb.getSelectedItem().toString();
             this.grade=this.SSU_Grade_cb.getSelectedItem().toString();
             this.sport=this.SSU_Sport_cb.getSelectedItem().toString();
            if(this.SSU_Male_radbtn.isSelected())
                this.gender="Male";
            else
                this.gender="Female";
        }    
    return flag;
    }
    public void getCoachId(){
        String name=this.SSU_Coach_txt.getText();
        
       String fname=name.toString().split(" ")[0];
     String lname=name.toString().split(" ")[1];
     
     try{
            
               Class.forName("java.sql.DriverManager"); //loading and registering drivers required for MYSQL
               
               Connection con=ConnectDB.getConnect();
               Statement s=con.createStatement();
                ResultSet r=s.executeQuery("select * from coach_details  where firstname='" +fname+"'  and lastname='"+lname+"'"); 
                if(r.next()){ 
                       
                    this.coachID=r.getInt("coach_id");
                 }
                
                 
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
     
     
    }
          
    private void SSU_Female_radbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSU_Female_radbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSU_Female_radbtnActionPerformed

    private void SSU_FormTutor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSU_FormTutor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSU_FormTutor_txtActionPerformed

    private void SSU_SchoolID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSU_SchoolID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSU_SchoolID_txtActionPerformed

    private void SSU_StudentID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSU_StudentID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSU_StudentID_txtActionPerformed

    private void SSU_Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSU_Reset_btnActionPerformed
       this.SSU_AgeGroup_cb.setSelectedItem("Select");
       this.SSU_House_cb.setSelectedItem("Select");
       this.SSU_Sport_cb.setSelectedItem("Select");
       this.SSU_Grade_cb.setSelectedItem("Select");
       this.SSU_FormTutor_txt.setText("");
       this.SSU_StudentID_txt.setText("");
       this.SSU_Female_radbtn.setSelected(false);
       this.SSU_Male_radbtn.setSelected(false);
    }//GEN-LAST:event_SSU_Reset_btnActionPerformed

    private void SSU_Sport_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSU_Sport_cbActionPerformed
     
         
        if(!this.SSU_Sport_cb.getSelectedItem().toString().equals("Select")){
        try{
            
               Class.forName("java.sql.DriverManager"); //loading and registering drivers required for MYSQL
               
               Connection con=ConnectDB.getConnect();
               Statement s=con.createStatement();
                ResultSet r=s.executeQuery("select * from coach_details  where sport='"+this.SSU_Sport_cb.getSelectedItem().toString()+"'"); 
                if(r.next()){ 
                       
                    this.SSU_Coach_txt.setText(r.getString("firstname")+" "+r.getString("lastname"));
                 }
                
                 
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }else
            JOptionPane.showMessageDialog(this, "Please select sport first");
        
    }//GEN-LAST:event_SSU_Sport_cbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SSD_Sport_lbl;
    private javax.swing.JComboBox<String> SSU_AgeGroup_cb;
    private javax.swing.JLabel SSU_AgeGroup_lbl;
    private javax.swing.JButton SSU_Back_btn;
    private javax.swing.JLabel SSU_Coach_lbl;
    private javax.swing.JTextField SSU_Coach_txt;
    private javax.swing.JRadioButton SSU_Female_radbtn;
    private javax.swing.JLabel SSU_FormTutor_lbl;
    private javax.swing.JTextField SSU_FormTutor_txt;
    private javax.swing.JPanel SSU_Gender_btn;
    private javax.swing.JComboBox<String> SSU_Grade_cb;
    private javax.swing.JLabel SSU_Grade_lbl;
    private javax.swing.JComboBox<String> SSU_House_cb;
    private javax.swing.JLabel SSU_House_lbl;
    private javax.swing.JRadioButton SSU_Male_radbtn;
    private javax.swing.JButton SSU_Reset_btn;
    private javax.swing.JLabel SSU_SchoolID_lbl;
    private javax.swing.JTextField SSU_SchoolID_txt;
    private javax.swing.JComboBox<String> SSU_Sport_cb;
    private javax.swing.JLabel SSU_StudentID_lbl;
    private javax.swing.JTextField SSU_StudentID_txt;
    private javax.swing.JButton SSU_Submit_btn;
    private javax.swing.JLabel STMS_lbl5;
    private javax.swing.JPanel StudentSignUpPanel;
    private javax.swing.JPanel StudentSignUpWholePanel;
    private javax.swing.ButtonGroup signup_Student_btngrp;
    // End of variables declaration//GEN-END:variables

    private void insertRecords() {
      
    try {
            Class.forName("java.sql.DriverManager"); //loading drivers to connect GUI with databse
            Connection c = ConnectDB.getConnect(); //getting connection with Sports_db
            Statement st = c.createStatement(); //enabling SQL statements  in java code
            
            int y = st.executeUpdate("insert into student_details values("+this.studentID + ",'" 
                    + this.firstName + "','" +this.lastName+"','"+this.grade+"','"+this.house+"','"+this.tutorName+"',"
                            + "'"+this.emailID+"','"+this.sport+"','"+this.ageGroup+"','"+this.gender+"',"
                                    +this.coachID+")"); 
            
            if (y > 0) {
                JOptionPane.showMessageDialog(this, "Congratulations! Your records are added to the database successfully"); 
               
                   LoginPage lp=new LoginPage();
                   lp.setVisible(true);
                this.dispose();
               
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }
}
