/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsteammgmtsystem;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sidbohra
 */
public class CoachSignUp extends javax.swing.JFrame {

    private int schoolID;
    private String firstName, lastName, sport, gender, emailID,contactNumber;
    public CoachSignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
  public CoachSignUp(String firstName, String lastName, String emailID) {
        initComponents();
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailID = emailID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentSignUpPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        signup_StudentBack_btn = new javax.swing.JButton();
        signup_StudentSubmit_btn = new javax.swing.JButton();
        signup_StudentReset_btn = new javax.swing.JButton();
        signup_StudentGender_btn = new javax.swing.JPanel();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        signup_StudentYearLvl_CB = new javax.swing.JComboBox<>();
        signup_StudentAG_CB = new javax.swing.JComboBox<>();
        signup_StudentFormTutor_txt = new javax.swing.JTextField();
        signup_StudentSport_CB = new javax.swing.JComboBox<>();
        signup_StudentCoach_CB = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        signup_StudentHouse_CB = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        signup_schoolID_txt = new javax.swing.JTextField();
        signup_StudentID_txt = new javax.swing.JTextField();
        signup_Coach_btngrp = new javax.swing.ButtonGroup();
        STMS_lbl3 = new javax.swing.JLabel();
        CoachSignUpPanel = new javax.swing.JPanel();
        CSU_Sport_lbl = new javax.swing.JLabel();
        CSU_back_btn = new javax.swing.JButton();
        CSU_Submit_btn = new javax.swing.JButton();
        CSU_Reset_btn = new javax.swing.JButton();
        CSU_GenderPanel = new javax.swing.JPanel();
        CSU_Male_radbtn = new javax.swing.JRadioButton();
        CSU_Female_radbtn = new javax.swing.JRadioButton();
        CSU_ContactNumber_lbl = new javax.swing.JLabel();
        CSU_Sport_cb = new javax.swing.JComboBox<>();
        CSU_ContactNumber_txt = new javax.swing.JTextField();

        StudentSignUpPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Student ID");

        jLabel32.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Sport");

        signup_StudentBack_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        signup_StudentBack_btn.setForeground(new java.awt.Color(0, 102, 102));
        signup_StudentBack_btn.setText("Back");
        signup_StudentBack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_StudentBack_btnActionPerformed(evt);
            }
        });

        signup_StudentSubmit_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        signup_StudentSubmit_btn.setForeground(new java.awt.Color(0, 102, 102));
        signup_StudentSubmit_btn.setText("Submit");
        signup_StudentSubmit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_StudentSubmit_btnActionPerformed(evt);
            }
        });

        signup_StudentReset_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        signup_StudentReset_btn.setForeground(new java.awt.Color(0, 102, 102));
        signup_StudentReset_btn.setText("Reset");
        signup_StudentReset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_StudentReset_btnActionPerformed(evt);
            }
        });

        signup_StudentGender_btn.setBackground(new java.awt.Color(255, 255, 255));
        signup_StudentGender_btn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N

        jRadioButton28.setText("Male");

        jRadioButton29.setText("Female");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signup_StudentGender_btnLayout = new javax.swing.GroupLayout(signup_StudentGender_btn);
        signup_StudentGender_btn.setLayout(signup_StudentGender_btnLayout);
        signup_StudentGender_btnLayout.setHorizontalGroup(
            signup_StudentGender_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signup_StudentGender_btnLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jRadioButton28)
                .addGap(37, 37, 37)
                .addComponent(jRadioButton29)
                .addGap(63, 63, 63))
        );
        signup_StudentGender_btnLayout.setVerticalGroup(
            signup_StudentGender_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signup_StudentGender_btnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signup_StudentGender_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton29))
                .addGap(38, 38, 38))
        );

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Coach");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Form Tutor");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Grade");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sports Age Group");

        signup_StudentYearLvl_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 7", "Year 8", "Year 9", "Year 10", "Year 11", "Year 12", "Year 13", " " }));

        signup_StudentAG_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U12", "U13", "U14", "U15", "U16", "U17", "U18" }));

        signup_StudentFormTutor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_StudentFormTutor_txtActionPerformed(evt);
            }
        });

        signup_StudentSport_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Volleyball", "Football", "Basketball", "Rugby", "Tennis", "Badminton", "Swimming", "Cross Country", "Table Tennis" }));

        signup_StudentCoach_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coach Travis", "Coach Fausset", "Coach Boak", "Coach Sexton", "Coach Siu", " ", " " }));

        jLabel33.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("House");

        signup_StudentHouse_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Da Vinci", "Einstein", "Fleming", "Nansen", "Rutherford", "Wilberforce", " " }));

        jLabel34.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("School ID");

        signup_schoolID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_schoolID_txtActionPerformed(evt);
            }
        });

        signup_StudentID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_StudentID_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentSignUpPanelLayout = new javax.swing.GroupLayout(StudentSignUpPanel);
        StudentSignUpPanel.setLayout(StudentSignUpPanelLayout);
        StudentSignUpPanelLayout.setHorizontalGroup(
            StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signup_StudentSport_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_StudentCoach_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_StudentFormTutor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_StudentYearLvl_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_StudentHouse_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_StudentID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signup_StudentAG_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                            .addComponent(signup_StudentSubmit_btn)
                            .addGap(38, 38, 38)
                            .addComponent(signup_StudentReset_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signup_StudentBack_btn))
                        .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(signup_schoolID_txt))
                        .addComponent(signup_StudentGender_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        StudentSignUpPanelLayout.setVerticalGroup(
            StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_StudentAG_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_StudentID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(signup_StudentSport_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(signup_StudentCoach_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(signup_StudentFormTutor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signup_StudentYearLvl_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signup_StudentHouse_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(StudentSignUpPanelLayout.createSequentialGroup()
                        .addComponent(signup_StudentGender_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signup_schoolID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(signup_StudentSubmit_btn)
                            .addComponent(signup_StudentReset_btn)
                            .addComponent(signup_StudentBack_btn))))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        STMS_lbl3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        STMS_lbl3.setForeground(new java.awt.Color(0, 102, 102));
        STMS_lbl3.setText("Sports Team Management System");

        CoachSignUpPanel.setBackground(new java.awt.Color(0, 102, 102));

        CSU_Sport_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        CSU_Sport_lbl.setForeground(new java.awt.Color(255, 255, 255));
        CSU_Sport_lbl.setText("Sport");

        CSU_back_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        CSU_back_btn.setForeground(new java.awt.Color(0, 102, 102));
        CSU_back_btn.setText("Back");
        CSU_back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSU_back_btnActionPerformed(evt);
            }
        });

        CSU_Submit_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        CSU_Submit_btn.setForeground(new java.awt.Color(0, 102, 102));
        CSU_Submit_btn.setText("Submit");
        CSU_Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSU_Submit_btnActionPerformed(evt);
            }
        });

        CSU_Reset_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        CSU_Reset_btn.setForeground(new java.awt.Color(0, 102, 102));
        CSU_Reset_btn.setText("Reset");
        CSU_Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSU_Reset_btnActionPerformed(evt);
            }
        });

        CSU_GenderPanel.setBackground(new java.awt.Color(255, 255, 255));
        CSU_GenderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N

        signup_Coach_btngrp.add(CSU_Male_radbtn);
        CSU_Male_radbtn.setText("Male");

        signup_Coach_btngrp.add(CSU_Female_radbtn);
        CSU_Female_radbtn.setText("Female");
        CSU_Female_radbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSU_Female_radbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CSU_GenderPanelLayout = new javax.swing.GroupLayout(CSU_GenderPanel);
        CSU_GenderPanel.setLayout(CSU_GenderPanelLayout);
        CSU_GenderPanelLayout.setHorizontalGroup(
            CSU_GenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CSU_GenderPanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(CSU_Male_radbtn)
                .addGap(37, 37, 37)
                .addComponent(CSU_Female_radbtn)
                .addGap(63, 63, 63))
        );
        CSU_GenderPanelLayout.setVerticalGroup(
            CSU_GenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CSU_GenderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CSU_GenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CSU_Male_radbtn)
                    .addComponent(CSU_Female_radbtn))
                .addGap(38, 38, 38))
        );

        CSU_ContactNumber_lbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        CSU_ContactNumber_lbl.setForeground(new java.awt.Color(255, 255, 255));
        CSU_ContactNumber_lbl.setText("Contact Number");

        CSU_Sport_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Volleyball", "Football", "Basketball", "Rugby", "Tennis", "Badminton", "Swimming", "Cross Country", "Table Tennis" }));

        CSU_ContactNumber_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSU_ContactNumber_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CoachSignUpPanelLayout = new javax.swing.GroupLayout(CoachSignUpPanel);
        CoachSignUpPanel.setLayout(CoachSignUpPanelLayout);
        CoachSignUpPanelLayout.setHorizontalGroup(
            CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoachSignUpPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CSU_Sport_lbl)
                    .addComponent(CSU_ContactNumber_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CSU_Sport_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CSU_ContactNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CSU_GenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CoachSignUpPanelLayout.createSequentialGroup()
                        .addComponent(CSU_Submit_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CSU_Reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(CSU_back_btn)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        CoachSignUpPanelLayout.setVerticalGroup(
            CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoachSignUpPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CoachSignUpPanelLayout.createSequentialGroup()
                        .addGroup(CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CSU_Sport_lbl)
                            .addComponent(CSU_Sport_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CSU_ContactNumber_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CSU_ContactNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CSU_GenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(CoachSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CSU_Submit_btn)
                    .addComponent(CSU_Reset_btn)
                    .addComponent(CSU_back_btn))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(STMS_lbl3)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CoachSignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(STMS_lbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoachSignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signup_StudentBack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_StudentBack_btnActionPerformed

    }//GEN-LAST:event_signup_StudentBack_btnActionPerformed

    private void signup_StudentSubmit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_StudentSubmit_btnActionPerformed

    }//GEN-LAST:event_signup_StudentSubmit_btnActionPerformed

    private void signup_StudentReset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_StudentReset_btnActionPerformed
     
    }//GEN-LAST:event_signup_StudentReset_btnActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void signup_StudentFormTutor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_StudentFormTutor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_StudentFormTutor_txtActionPerformed

    private void signup_schoolID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_schoolID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_schoolID_txtActionPerformed

    private void signup_StudentID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_StudentID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_StudentID_txtActionPerformed

    private void CSU_back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSU_back_btnActionPerformed
      SignUp lp=new SignUp(); 
            lp.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_CSU_back_btnActionPerformed

    private void CSU_Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSU_Submit_btnActionPerformed

        if(validateEntries()==true)
        insertRecords();  ///insert in db table student_details
    }//GEN-LAST:event_CSU_Submit_btnActionPerformed
    public boolean validateEntries(){
    boolean flag=true;
    if(this.CSU_Sport_cb.getSelectedItem().toString().equals("Select")){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please select your Sport");      
        } else if (this.CSU_ContactNumber_txt.getText().isEmpty()){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please enter your Contact Number");
        } else if(this.CSU_Sport_cb.getSelectedItem().toString().equals("Select")){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please select your Sport");      
        } else if(!this.CSU_Male_radbtn.isSelected() && !this.CSU_Female_radbtn.isSelected()){
            flag=false;
            JOptionPane.showMessageDialog(this, "Please Select Your Gender");}
         
    
    if(flag){
            this.schoolID=600707;
            this.sport=this.CSU_Sport_cb.getSelectedItem().toString();
            this.contactNumber = this.CSU_ContactNumber_txt.getText();
            if(this.CSU_Male_radbtn.isSelected())
                this.gender="Male";
            else
                this.gender="Female";
        }    
    return flag;
    }
    private void CSU_Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSU_Reset_btnActionPerformed
        this.CSU_ContactNumber_txt.setText("");
        this.CSU_Sport_cb.setSelectedItem("Select");
        this.CSU_Female_radbtn.setSelected(false);
        this.CSU_Male_radbtn.setSelected(false);
    }//GEN-LAST:event_CSU_Reset_btnActionPerformed

    private void CSU_Female_radbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSU_Female_radbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSU_Female_radbtnActionPerformed

    private void CSU_ContactNumber_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSU_ContactNumber_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSU_ContactNumber_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoachSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoachSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoachSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoachSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoachSignUp().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CSU_ContactNumber_lbl;
    private javax.swing.JTextField CSU_ContactNumber_txt;
    private javax.swing.JRadioButton CSU_Female_radbtn;
    private javax.swing.JPanel CSU_GenderPanel;
    private javax.swing.JRadioButton CSU_Male_radbtn;
    private javax.swing.JButton CSU_Reset_btn;
    private javax.swing.JComboBox<String> CSU_Sport_cb;
    private javax.swing.JLabel CSU_Sport_lbl;
    private javax.swing.JButton CSU_Submit_btn;
    private javax.swing.JButton CSU_back_btn;
    private javax.swing.JPanel CoachSignUpPanel;
    private javax.swing.JLabel STMS_lbl3;
    private javax.swing.JPanel StudentSignUpPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.ButtonGroup signup_Coach_btngrp;
    private javax.swing.JComboBox<String> signup_StudentAG_CB;
    private javax.swing.JButton signup_StudentBack_btn;
    private javax.swing.JComboBox<String> signup_StudentCoach_CB;
    private javax.swing.JTextField signup_StudentFormTutor_txt;
    private javax.swing.JPanel signup_StudentGender_btn;
    private javax.swing.JComboBox<String> signup_StudentHouse_CB;
    private javax.swing.JTextField signup_StudentID_txt;
    private javax.swing.JButton signup_StudentReset_btn;
    private javax.swing.JComboBox<String> signup_StudentSport_CB;
    private javax.swing.JButton signup_StudentSubmit_btn;
    private javax.swing.JComboBox<String> signup_StudentYearLvl_CB;
    private javax.swing.JTextField signup_schoolID_txt;
    // End of variables declaration//GEN-END:variables

    private void insertRecords() {
      
    try {
            Class.forName("java.sql.DriverManager"); //loading drivers to connect GUI with databse
            Connection c = ConnectDB.getConnect(); //getting connection with Sports_db
            Statement st = c.createStatement(); //enabling SQL statements  in java code
            
            int y = st.executeUpdate("insert into coach_details(firstname, lastname, contact_number, sport, gender, email_id) values('" + this.firstName + "','" + this.lastName + "','" + this.contactNumber + "','" + this.sport + "','" + this.gender + "','" + this.emailID + "')");
                     
            
            if (y > 0) {
                JOptionPane.showMessageDialog(this, "Congratulations! Your records are added to the database successfully"); 
               
                   LoginPage lp=new LoginPage();
                   lp.setVisible(true);
                this.dispose();
               
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }

}
