/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package sportsteammgmtsystem;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sidbohra
 */
public class ConsentFormsDashboard extends javax.swing.JFrame {

   private int fixtureid;
    public ConsentFormsDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
 public ConsentFormsDashboard(int fixtureid) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fixtureid=fixtureid;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoachMyFixturePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgforparents_txt = new javax.swing.JTextArea();
        CFD_SubmitConsentForm_btn = new javax.swing.JButton();
        CFD_back_btn = new javax.swing.JButton();
        STMS_lbl3 = new javax.swing.JLabel();
        STMS_lbl4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CoachMyFixturePanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Message for Parents ");

        msgforparents_txt.setColumns(20);
        msgforparents_txt.setRows(5);
        jScrollPane1.setViewportView(msgforparents_txt);
        msgforparents_txt.getAccessibleContext().setAccessibleName("Consent Form Message");
        msgforparents_txt.getAccessibleContext().setAccessibleDescription("");

        CFD_SubmitConsentForm_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        CFD_SubmitConsentForm_btn.setForeground(new java.awt.Color(0, 102, 102));
        CFD_SubmitConsentForm_btn.setText("Submit");
        CFD_SubmitConsentForm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFD_SubmitConsentForm_btnActionPerformed(evt);
            }
        });

        CFD_back_btn.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        CFD_back_btn.setForeground(new java.awt.Color(0, 102, 102));
        CFD_back_btn.setText("Back");
        CFD_back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFD_back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CoachMyFixturePanelLayout = new javax.swing.GroupLayout(CoachMyFixturePanel);
        CoachMyFixturePanel.setLayout(CoachMyFixturePanelLayout);
        CoachMyFixturePanelLayout.setHorizontalGroup(
            CoachMyFixturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoachMyFixturePanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(CoachMyFixturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(CFD_SubmitConsentForm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CFD_back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        CoachMyFixturePanelLayout.setVerticalGroup(
            CoachMyFixturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoachMyFixturePanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(CFD_SubmitConsentForm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CFD_back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoachMyFixturePanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        STMS_lbl3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        STMS_lbl3.setForeground(new java.awt.Color(0, 102, 102));
        STMS_lbl3.setText("Sports Team Management System");

        STMS_lbl4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        STMS_lbl4.setForeground(new java.awt.Color(0, 102, 102));
        STMS_lbl4.setText("Consent Form Creation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CoachMyFixturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(STMS_lbl4)
                                .addGap(256, 256, 256))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(STMS_lbl3)
                                .addGap(197, 197, 197))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(STMS_lbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(STMS_lbl4)
                .addGap(18, 18, 18)
                .addComponent(CoachMyFixturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CFD_SubmitConsentForm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFD_SubmitConsentForm_btnActionPerformed
       
        
        if(this.msgforparents_txt.getText().isEmpty()){
            //show error 
        }else{
            
             try {
            Class.forName("java.sql.DriverManager"); //loading drivers to connect GUI with databse
            Connection c = ConnectDB.getConnect(); //getting connection with Sports_db
            Statement st = c.createStatement(); //enabling SQL statements  in java code
            
            int y = st.executeUpdate("insert into parentalconsent_details values("+this.fixtureid+",'"+this.msgforparents_txt.getText() + "')"); 
            
            if (y > 0) {
                JOptionPane.showMessageDialog(this, "Message is sent"); 
               
                   AllUpcomingFixtures lp=new AllUpcomingFixtures(LoginPage.name);
                   lp.setVisible(true);
                this.dispose();
               
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
            
            
            
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_CFD_SubmitConsentForm_btnActionPerformed

    private void CFD_back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFD_back_btnActionPerformed
        CoachMyFixture cmf = new CoachMyFixture();
        cmf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CFD_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsentFormsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsentFormsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsentFormsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsentFormsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsentFormsDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CFD_SubmitConsentForm_btn;
    private javax.swing.JButton CFD_back_btn;
    private javax.swing.JPanel CoachMyFixturePanel;
    private javax.swing.JLabel STMS_lbl3;
    private javax.swing.JLabel STMS_lbl4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgforparents_txt;
    // End of variables declaration//GEN-END:variables

}
